<header class="homepage-header">
    <div class="logo-box"><img src="img/logo.png" alt="logo de Dynasty Patrimoine" class="logo"></div>
    <div class="welcome-bar">
        <h3>Bienvenue</h3>
    </div>
</header>

<div class="form-container">
    <div class="form-box">
        <form>
            <div class="input-items">
                <label>Numéro de lot:</label>
                <input type="text" placeholder="84500">
            </div>

            <div class="input-items">
                <label>Type d'appartement:</label>
                <input type="text" placeholder="T3">
            </div>
            
            <div class="input-items">
                <label>Prix appartement:</label>
                <input type="text" placeholder="200 000">
            </div>

            <div class="input-items">
                <label>Prix garage ou autre:</label>
                <input type="text" placeholder="10 000">
            </div>

            <div class="input-items">
                <label>Loyer mensuel brut:</label>
                <input type="text" placeholder="750">
            </div>

            <div class="input-items">
                <label>Surface:</label>
                <input type="text" placeholder="67">
            </div>

            <div class="input-items">
                <label>Frais de notaire:</label>
                <input type="text" placeholder="5 275">
            </div>

            <div class="input-items">
                <label>Montant de l'apport:</label>
                <input type="text" placeholder="0">
            </div>

            <div class="input-items">
                <label>Montant du financement:</label>
                <input type="text" placeholder="218 807">
            </div>

            <div class="input-items">
                <label>Montant de l'impôt:</label>
                <input type="text" placeholder="9000">
            </div>

            <div class="input-items">
                <label>Prêt amortissable/mensualité:</label>
                <input type="text" placeholder="927">
            </div>

            <div class="input-items">
                <label>Taux d'intêret/mensualité:</label>
                <input type="text" placeholder="2,00">
            </div>

            <div class="input-items">
                <label>Caution bancaire:</label>
                <input type="text" placeholder="2 532">
            </div>

            <div class="input-items">
                <label>Inflation previsionnelle:</label>
                <input type="text" placeholder="0.5%">
            </div>

            <div class="input-items">
                <label>TMI:</label>
                <input type="text" placeholder="30%">
            </div>

            <div class="input-items">
                <label>CSG/CRDS:</label>
                <input type="text" placeholder="17,2%">
            </div>

            <div class="button-box">
                <button type="submit" class="submitButton bttn-animation">Générer ma présentation</button>
            </div>
            
        </form>
        
        
    </div>
</div>

<footer>
    <div class="logo-box"><img src="img/logo.png" alt="logo de Dynasty Patrimoine" class="logo"></div>
    <p class="reveal">Dynasty Patrimoine - Copyright 2021 Tous droits réservés</p>
</footer>