<!DOCTYPE html>
<html lang="fr">
	<head>
    <!-- SEO -->
	<meta charset="utf-8"/>
    <meta name="description" content=""/>
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="patrimoine">
    <title>Dynastie Patrimoine Excell Project</title>
    <!-- CSS  -->
    <link rel="icon" type="images/vg" sizes="16x16" href="img/first.svg">
    <link rel="stylesheet" type="text/css" href="css/style.css">
  </head>
  
<body>

  <main>
      <?php require $page ?>
  </main>
    
  <!-- Scripts -->
  <script defer src="./js/app.js" ></script>
</body>
</html>

